// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYb7num4cWTJAH3eD5zbThPnktQETWZE4',
    appId: '1:308053571110:web:f9adaba84da62f50ce98e7',
    messagingSenderId: '308053571110',
    projectId: 'stocklastversion',
    authDomain: 'stocklastversion.firebaseapp.com',
    storageBucket: 'stocklastversion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPlEJw5M4AKzbJC5kZDFtbD02WkRzhO0s',
    appId: '1:308053571110:android:6d24253432d5108bce98e7',
    messagingSenderId: '308053571110',
    projectId: 'stocklastversion',
    storageBucket: 'stocklastversion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-BHoRYCT_Zg0OQHUQqNak-Vt_dfoQuiM',
    appId: '1:308053571110:ios:760fcfb4e3e7ab83ce98e7',
    messagingSenderId: '308053571110',
    projectId: 'stocklastversion',
    storageBucket: 'stocklastversion.firebasestorage.app',
    iosBundleId: 'com.example.stockmanagementversion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-BHoRYCT_Zg0OQHUQqNak-Vt_dfoQuiM',
    appId: '1:308053571110:ios:760fcfb4e3e7ab83ce98e7',
    messagingSenderId: '308053571110',
    projectId: 'stocklastversion',
    storageBucket: 'stocklastversion.firebasestorage.app',
    iosBundleId: 'com.example.stockmanagementversion2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYb7num4cWTJAH3eD5zbThPnktQETWZE4',
    appId: '1:308053571110:web:b0e343fc6768b2aace98e7',
    messagingSenderId: '308053571110',
    projectId: 'stocklastversion',
    authDomain: 'stocklastversion.firebaseapp.com',
    storageBucket: 'stocklastversion.firebasestorage.app',
  );
}
